import numpy as np
students = np.array(["Aayush", "Rahul", "Priya", "Ankit", "Sneha"])
subjects = np.array(["Python", "Maths", "DSA"])
np.random.seed(15)
marks = np.random.randint(40, 100, size=(len(students), len(subjects)))
print("Students:", students)
print("Subjects:", subjects)
print("Marks:")
print(marks)
average = np.mean(marks, axis=0).astype(int)
print("Average marks of students: ")
print(average)
median = np.median(marks,axis=0).astype(int)
print("Median marks of the students: ")
print(median)
std=np.std(marks, axis=0).astype(int)
print("Standard deviation in marks of each student: ")
print(std)